### ISSUE TITLE
new cli upload doesn't seem to work

### ISSUE THREAD

**Issue by jlmitch5** [monome/druid#47] opened 2019-10-20 02:10 UTC
I was trying to run

`druid upload ../bowery/shiftregister.lua`

and it opened the druid repl (but didn't seem to upload the script).  Note I was using the latest druid (master), build using the dev readme instructions.

I `git checkout`'d back to the commit https://github.com/monome/druid/commit/2d496f1537ee1ef497c930ba15395fe681f1def0, and ran the old way:

python3 upload.py ../bowery/shiftregister.lua

```
 uploading ../bowery/shiftregister.lua

lua bootstrapped
input loaded
asl loaded
asllib loaded
metro loaded
ii loaded
crowlib loaded
^^change(2,1)
^^change(2,1)

 file uploaded:
jf loaded
--- digital analog shift register
-- four stages of delay for an incoming cv
-- input 1: cv to delay
-- input 2: trigger to capture input & shift
-- output 1-4: newest to oldest output
-- ii: 6 stages of ASR via just friends

reg = {}
reg_LEN = 4

q = {}
function init()
    for n=1,4 do
        output[n].slew = 0
    end
    input[1].mode('none')
    input[2]{ mode      = 'change'
            , direction = 'rising'
            }
    for i=1,reg_LEN do
        reg[i] = input[1].volts
    end
    ii.pullup(true)
    ii.jf.mode(1)
    metro[1].event = iiseq
    metro[1].time  = 0.005
    metro[1]:start()
end

-- hack to allow 6note polyphony by staggering with metro
function iiseq()
    if #q > 0 then
        ii.jf.play_note(table.remove(q),2)
    end
end

function update(r)
    for n=1,4 do
        output[n].volts = r[n]
    end
    for n=1,6 do
        table.insert(q, r[n]) -- queue a note for i2c transmission
    end
end

input[2].change = function()
    capture = input[1].volts
    table.remove(reg)
    table.insert(reg, 1, input[1].volts)
    update(reg)
end
```

which works.  Not sure what's up with the new CLI (or maybe I am running things incorrectly?)

**Comment by csboling** [comment] 2019-10-20 03:03
This should work, but I'm unable to get consistent uploads from either `druid upload x.lua` or `python upload.py x.lua` on OSX. The code is almost exactly the same. What happens for you when the upload doesn't work? I see something from the following set of behaviors:
* druid continues to work okay as a REPL after upload
* druid will run, but some functionality does not work - like maybe I can print the uploaded script, but Lua typed in to the REPL does not evaluate. sometimes in this state I am able to run `^^r` to reset crow, after which Lua is working again.
* crow hangs completely, can't ctrl-C out of upload until unplugging USB, then after replugging druid can't find crow device and can't be used until I power cycle

**Comment by simonvanderveldt** [comment] 2019-10-25 10:20
@jlmitch5 Can you give this a try with druid 0.2.0?
Update procedure for reference:
```
# Update
$ pip install --upgrade monome-druid
# Check version
$ druid --version
druid, version 0.2.0
```

**Comment by simonvanderveldt** [comment] 2019-11-01 13:04
I'm going to go ahead an close this since I can't reproduce this and don't see a way this could happen.
If it's still happening on the current release feel free to reopen the issue/comment.

**Closed by simonvanderveldt** 2019-11-01 13:04 UTC
